# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'XXBVoicePlayer' do
    pod 'XXBLibs', :git => "https://github.com/sixTiger/XXBLibs"
#    pod 'mp3lame-for-ios'
end

